spring:
  aop:
    proxy-target-class: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
zeus:
  datasource:
    db:
      namespace: ${datasource.druid.url}
      username: ${datasource.druid.username}
      password: ${datasource.druid.password}
      dbName: ${datasource.druid.driver-class-name}
      min-idle-size: 30
      max-pool-size: 100
      minEvictableIdleTimeMillis: 600000
      timeBetweenEvictionRunsMillis: 120000
    redisson:
      address: ${redis.address}
      database: ${redis.database}
      password: ${redis.password}
      timeout: ${redis.timeout}
      minIdle: ${redis.pool.minIdle}
      maxIdle: ${redis.pool.maxIdle}
      maxTotal: ${redis.pool.maxTotal}
      maxWaitMillis: ${redis.pool.maxWaitMillis}